apiVersion: v1
kind: Service
metadata:
  name: wordpress-research-mysql
  namespace: websites
  labels:
    app: wordpress-research
spec:
  ports:
  - port: 3306
  selector:
    app: wordpress-research-mysql
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wordpress-research-mysql
  namespace: websites
  labels:
    app: wordpress-research
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-research-mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: research
              key: mysql-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-research-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-research-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-research-pv-claim
