apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-research-pv-claim
  namespace: websites
  labels:
    app: wordpress-research
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1.5Gi
